### ISSUE TITLE
`path` conflicts with secondary `source` in Gemfile

### ISSUE THREAD

**Issue by harto** [bundler/bundler#3414]
See https://gist.github.com/harto/0dfcee489e248900feb8 for reproduction.

Suppose a Gemfile references one gem from a local `path` and another from a secondary `source`, e.g.:
```
source "https://rubygems.org"
gem "local_gem", path: "local_gem"
gem "other_gem", source: "https://gems.example.com"
```

If I `bundle install`, the dependencies are apparently resolved and installed correctly. However, the bundle fails at runtime:
```
$ bundle exec ruby -e 'puts "hello"'
Could not find gem 'other_gem (>= 0) ruby' in rubygems repository https://gems.example.com/.
Source does not contain any versions of 'other_gem (>= 0) ruby'
Run `bundle install` to install missing gems.
```

Removing `local_gem` and running `bundle install` again appears to fix the problem:
```
$ bundle exe ruby -e 'puts "hello"'
hello
```

The `local_gem` doesn't have any dependencies. Again, see https://gist.github.com/harto/0dfcee489e248900feb8 for a minimal complete example.

**Comment by pda** [comment]
Confirmed in RubyGems 1.8.0 and 1.8.2.

**Comment by sheerun** [comment]
It breaks our service: https://github.com/rails-assets/rails-assets

**Comment by eagletmt** [comment]
Same here.

I found reverting https://github.com/bundler/bundler/commit/9263e08636d25e2573776b17416e6fabd403026b solves the issue in my environment.

**Comment by eagletmt** [comment]
Same here.

I found reverting https://github.com/bundler/bundler/commit/9263e08636d25e2573776b17416e6fabd403026b solves the issue in my environment.

**Comment by TimMoore** [comment]
I have a proposed fix at #3427. If fixes the test cases here and in #3417, but if you could try it on your real-world projects too, that would be awesome.

**Comment by TimMoore** [comment]
This should be fixed in Bundler 1.8.3 (released today).

**Comment by eagletmt** [comment]
I tried Bundler 1.8.3, but the same error still occurs in my environment.

**Comment by TimMoore** [comment]
@eagletmt can you create a new issue and include the output from `bundle env`?

**Comment by eagletmt** [comment]
I'll submit a new issue after a bit more investigation.

**Comment by eagletmt** [comment]
@TimMoore submitted #3430
