### ISSUE TITLE
`bundle update` installs yanked gems

### ISSUE THREAD

**Issue by sferik** [bundler/bundler#3500]
`bundle update` should install the latest version of a gem **unless it has been yanked**. The new resolver in Bundler 1.9 does not seem to respect this rule.

**Comment by segiddins** [comment]
@sferik can you please share a reproduction case? (A Gemfile + Lockfile)

**Comment by sferik** [comment]
@segiddins Sure. Here’s the project I discovered the bug on: https://github.com/sferik/sign-in-with-twitter/blob/master/Gemfile.lock.

If you clone that repo and type `bundle update`, it will install `ruby-progressbar` version 1.7.4, even though that version has been [yanked](https://rubygems.org/gems/ruby-progressbar/versions).

**Comment by indirect** [comment]
For the record, the desired behavior is installing yanked gems if they are already locked, but never locking to a gem that has been yanked. (That said, we have never installed yanked gem before, even when locked, so it's not required :P)

**Comment by segiddins** [comment]
I'll take a look at fixing this later -- shouldn't be too hard, as long as the info on whether a gem is yanked or not is available.

**Comment by segiddins** [comment]
@sferik just out of curiosity, is this issue present on 1.8?

**Comment by segiddins** [comment]
For some reason, the gem is still there in the dependency endpoint: http://bundler.rubygems.org/api/v1/dependencies.json?gems=ruby-progressbar.

**Comment by eins78** [comment]
This happened to me as well. This also happens on just `bundle install` if one starts fresh; it even **locks** the yanked version. Bundler version 1.9.1 

Minimal Repro:

```sh
mkdir /tmp/testcase
cd /tmp/testcase/
echo '2.1.5' > .ruby-version
echo "source 'http://rubygems.org'" > Gemfile
echo "gem 'rubocop'" >> Gemfile
bundle
grep progres Gemfile.lock
curl 'https://rubygems.org/gems/ruby-progressbar/versions' | grep -ni5 yank
```

**Comment by segiddins** [comment]
@indirect this seems to me to be a bundler-api error?

**Comment by indirect** [comment]
Looks like the API is somehow out of sync with the main database. We'll need to re-sync it by hand.

**Comment by indirect** [comment]
Argh I am defeated and give up. @arthurnn, can you help me figure out why this gem is still showing up in the API output even though the database has it marked as `indexed: false`?

**Comment by indirect** [comment]
This is fixed on the API thanks to @arthurnn. @segiddins, if you want to implement installing yanked gems as long as they're locked, go for it. :stuck_out_tongue_winking_eye:

**Comment by betesh** [comment]
I am having this issue right now with a gem I yanked about an hour ago.  I've yanked other gems before and I've never seen bundler try to install it again, even seconds later.

    $ gem list openmarket --remote --all
    
    *** REMOTE GEMS ***
    
    openmarket (0.0.3, 0.0.2, 0.0.1)

    $ cat Gemfile
    source "https://rubygems.org/"

    gem "openmarket"

    $ bundle
    $ cat Gemfile.lock
    GEM
      remote: https://rubygems.org/
      specs:
        builder (3.2.2)
        httparty (0.13.5)
          json (~> 1.8)
          multi_xml (>= 0.5.2)
        json (1.8.3)
        multi_xml (0.5.5)
        openmarket (0.0.4)
          builder
          httparty
          sms_validation (~> 0.0.2)
        sms_validation (0.0.2)

    PLATFORMS
      ruby

    DEPENDENCIES
      openmarket

    BUNDLED WITH
      1.10.3


I even ran `rvm implode` and then re-installed RVM just to make sure there was no cached gemspec somewhere locally.  No improvement.

The only thing that solves the problem (other than adding version restrictions to the Gemfile) is running `bundle` with the `--full-index` option.

**Comment by a-barbieri** [comment]
Same issue as @betesh. `bundle --full-index` didn't solve it. I had to bump a new release which makes yanking version useless...

**Comment by colby-swandale** [comment]
@a-barbieri Please open an new issue with the details of your problem, you can follow Bundler's [ISSUES](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) guide for more information.
