### ISSUE TITLE
Bundle install with path and excluding a group fails when Gemfile.lock is present.

### ISSUE THREAD

**Issue by paresharma** [bundler/bundler#3981]
Here is my Gemfile and Gemfile.lock:

```ruby
#Gemfile
source 'https://rubygems.org'
gem 'json', github: 'flori/json', group: :development
```

```ruby
#Gemfile.lock
GIT
  remote: git://github.com/flori/json.git
  revision: f7394adf3a50631b443135a95ec1bc9d8b8f32ab
  specs:
    json (1.8.3)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  json!

BUNDLED WITH
   1.10.6
```

The following command fails if we don't have the gem from Github already checkout in `vendor/bundle`.

`bundle install --path=vendor/bundle --without development`

It works if the Gemfile.lock is not present. Removing the Gemfile.lock is a work around.

Shouldn't this work or is there anything I'm doing wrong?

**Comment by TimMoore** [comment]
Fails how? Can you please paste the output?

**Comment by paresharma** [comment]
Hi, here is the output. This only happens when we try to do a bundle install locally without a group that has gem from git.
```
bundle install --path=vendor/bundle --without development
git://github.com/flori/json.git (at master) is not yet checked out. Run `bundle install` first.
Bundler gave the error "git://github.com/flori/json.git (at master) is not yet checked out. Run `bundle install` first." while processing "/Users/pareshsharma/Workspace/xtra/test/Gemfile". Perhaps you forgot to run "bundle install"?
```

**Comment by agis-** [comment]
I could reproduce the error following the steps you've described.

With a little digging, it seems that [`#resolve_if_need`](https://github.com/bundler/bundler/blob/master/lib/bundler/installer.rb#L271-L284) doesn't actually resolves the depencies when it should, or? This happens because `local` is set to `true`:

```ruby
# ...
begin
  tmpdef = Definition.build(Bundler.default_gemfile, Bundler.default_lockfile, nil)
  # `tmpdef.missing_specs` is empty therefore `local` is set to `true`
  true unless tmpdef.new_platform? || tmpdef.missing_specs.any?
rescue BundlerError
end
# ...
```

I'm not sure however if JSON in that case should appear as a missing spec, since `--without` actually downloads but doesn't install the gems.

**Comment by indirect** [comment]
I think that missing_specs should have `json` in it if the gem is in the Bundle; the installer will skip installing the gem later if it's in a without group.

**Comment by RochesterinNYC** [comment]
Verified that this has been fixed in `v1.11.2`.

```bash
$ bundle install --path=vendor/bundle --without development
Fetching git://github.com/flori/json.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using bundler 1.11.2
Bundle complete! 1 Gemfile dependency, 1 gem now installed.
Gems in the group development were not installed.
Bundled gems are installed into ./vendor/bundle.
```

**Comment by paresharma** [comment]
@RochesterinNYC The issue still persists with v1.11.2. Please find below the trace for the same.

```
➜ ll
total 16
-rw-r--r--  1 paresharma  staff    84B Mar  5 22:10 Gemfile
-rw-r--r--  1 paresharma  staff   235B Mar  5 22:15 Gemfile.lock
drwxr-xr-x  3 paresharma  staff   102B Mar  5 22:12 vendor

➜ cat Gemfile
source 'https://rubygems.org'
gem 'json', github: 'flori/json', group: :development

➜ cat Gemfile.lock
GIT
  remote: git://github.com/flori/json.git
  revision: f7394adf3a50631b443135a95ec1bc9d8b8f32ab
  specs:
    json (1.8.3)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  json!

BUNDLED WITH
   1.11.2

➜ bundle --version
Bundler version 1.11.2

➜ bundle install --path=vendor/bundle --without development
git://github.com/flori/json.git (at master@f7394ad) is not yet checked out. Run `bundle install` first.
```

**Comment by RochesterinNYC** [comment]
Okay, apologies. The exact `Gemfile.lock` you had was necessary to reproduce this.

Quick question, what is the intended/expected behavior here? That this would be essentially a no-op because of the `--without development`?

**Comment by asutoshpalai** [comment]
@RochesterinNYC: Hi, I am interested in resolving this

**Comment by RochesterinNYC** [comment]
@asutoshpalai sure, go ahead.

**Comment by indirect** [comment]
Running `bundle install` should check out git repos that are missing—it shouldn't be possible to get the "not checked out yet" error while running the `install` command. Theoretically, git repos should not be checked out if you also pass the `--local` option, but that is currently not implemented. This is definitely a bug.

**Comment by RochesterinNYC** [comment]
@asutoshpalai please let me know if you intend on resolving this, as I already might have a fix.

**Comment by asutoshpalai** [comment]
Yes, I am still interested in resolving this, but I see that there is a already pull request for a related issue.
Sorry for the delay, I was stuck in some inevitable circumstances. Should I still go ahead on this?

**Comment by RochesterinNYC** [comment]
If you're referring to #4353, that is a pull request for something different than this exact issue (it's related to the part of @indirect's [comment](https://github.com/bundler/bundler/issues/3981#issuecomment-193899340).

**Comment by asutoshpalai** [comment]
Yes, indirect's comment made me think so, my bad.  I had investigated the issue a bit and now I am writing a failing spec for this issue.

**Comment by asutoshpalai** [comment]
`bundle install --path=vendor/bundle` fails because `bundle install --path=vendor/bundle --without development` is ran once and so it is added to the `.bundle/config`. Then running `bundle install --path=vendor/bundle` actually run without the group development. If you run it on a fresh reproduction of the issue, it runs fine.
