### ISSUE TITLE
Bundler not working on my system for some reason

### ISSUE THREAD

**Issue by ChristopherVH** [bundler/bundler#4431]
Christophers-MacBook-Pro:assoc-skeleton chrisvh$ bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/chrisvh/.rbenv/versions/2.1.2/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install the required ruby gems

- What happened instead?

  Instead, what actually happened was it gave this error message

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /Users/chrisvh/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `initialize'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `open'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `open'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `update'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:63:in `update'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:54:in `update_and_parse_checksums!'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/fetcher/compact_index.rb:63:in `available?'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/fetcher.rb:154:in `use_api'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/source/rubygems.rb:331:in `select'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/index.rb:10:in `build'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/source/rubygems.rb:82:in `specs'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/spec_set.rb:91:in `block in materialize'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/spec_set.rb:88:in `map!'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/spec_set.rb:88:in `materialize'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/definition.rb:140:in `specs'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/installer.rb:70:in `run'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/installer.rb:22:in `install'
      /usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/cli/install.rb:106:in `run'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/cli.rb:173:in `install'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/cli.rb:11:in `start'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/exe/bundle:27:in `block in <top (required)>'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.pre.1/exe/bundle:19:in `<top (required)>'
      /Users/chrisvh/.rbenv/versions/2.1.2/bin/bundle:23:in `load'
      /Users/chrisvh/.rbenv/versions/2.1.2/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.12.0.pre.1
  Rubygems  2.2.2
  Ruby      2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin15.0]
  GEM_HOME  /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
  GEM_PATH  /Users/chrisvh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0:/Users/chrisvh/.gem/ruby/2.1.0
  Git       2.7.1
--- TEMPLATE END ----------------------------------------------------------------

**Comment by bronzdoc** [comment]
Seems like you don't have read permissions on
 ```/Users/username/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions```
change your permision to that file so you can read it, or check how https://github.com/bundler/bundler/issues/4429 was fixed, since is related.

**Comment by RochesterinNYC** [comment]
Hi @ChristopherVH did @bronzdoc's suggestion fix your issue?

**Comment by ChristopherVH** [comment]
No I'm still having issues with the bundler and have no idea how to change read or write permissions tp that file.

**Comment by ChristopherVH** [comment]
Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/pg-0.18.4

An error occurred while installing bcrypt (3.1.10), and Bundler cannot continue.
Make sure that `gem install bcrypt -v '3.1.10'` succeeds before bundling.

**Comment by lynnco** [comment]
Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93) `Permission denied @ dir_s_mkdir` issues. Permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14
