### ISSUE TITLE
ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work

### ISSUE THREAD

**Issue by ZachSaucier** [bundler/bundler#4630]
I'm attempting to install bundler using the new Ubuntu bash in the Windows 10 preview. However, I ran into the following issue (It may be related to [issue #4599](https://github.com/bundler/bundler/issues/4599)?) using both the Bash.exe and PowerShell running the bash:
- What did you do?
  
  I ran the command `/usr/local/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to install the necessary dependencies
- What happened instead?
  
  Instead, what actually happened was the error below

```
Error details

    ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/home/zeaklo
us/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160531-680-yu1a8t" (parent di
rectory mode 40777)
      /usr/lib/ruby/1.9.1/fileutils.rb:708:in `remove_entry_secure'
      /usr/lib/ruby/1.9.1/tmpdir.rb:85:in `ensure in mktmpdir'
      /usr/lib/ruby/1.9.1/tmpdir.rb:85:in `mktmpdir'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.r
b:29:in `update'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in
`update'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in
`update_and_parse_checksums!'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request
'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:91:in `block in materialize'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  1.8.23
  Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
  GEM_HOME  /var/lib/gems/1.9.1
  GEM_PATH  /var/lib/gems/1.9.1:/home/zeaklous/.gem/ruby/1.9.1
  Git       1.9.1

      Bundler settings

  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

`bundle env` produced the following:

```
Bundler settings

    orig_path
      Set via BUNDLE_ORIG_PATH: "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"

Gemfile

    source "https://rubygems.org"

    group :development do
      gem 'rake', '~> 0.9'
      gem 'jekyll', '~> 0.12'
      gem 'rdiscount', '~> 2.0.7'
      gem 'pygments.rb', '~> 0.3.4'
      gem 'RedCloth', '~> 4.2.9'
      gem 'haml', '~> 3.1.7'
      gem 'compass', '~> 0.12.2'
      gem 'sass', '~> 3.2'
      gem 'sass-globbing', '~> 1.0.0'
      gem 'rubypants', '~> 0.2.0'
      gem 'rb-fsevent', '~> 0.9'
      gem 'stringex', '~> 1.4.0'
      gem 'liquid', '~> 2.3.0'
      gem 'directory_watcher', '1.4.1'
    end

    gem 'sinatra', '~> 1.4.2'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        RedCloth (4.2.9)
        RedCloth (4.2.9-x86-mingw32)
        chunky_png (1.2.5)
        classifier (1.3.3)
          fast-stemmer (>= 1.0.0)
        compass (0.12.2)
          chunky_png (~> 1.2)
          fssm (>= 0.2.7)
          sass (~> 3.1)
        directory_watcher (1.4.1)
        fast-stemmer (1.0.1)
        fssm (0.2.9)
        haml (3.1.7)
        jekyll (0.12.0)
          classifier (~> 1.3)
          directory_watcher (~> 1.1)
          kramdown (~> 0.13.4)
          liquid (~> 2.3)
          maruku (~> 0.5)
          pygments.rb (~> 0.3.2)
        kramdown (0.13.8)
        liquid (2.3.0)
        maruku (0.6.1)
          syntax (>= 1.0.0)
        posix-spawn (0.3.6)
        pygments.rb (0.3.4)
          posix-spawn (~> 0.3.6)
          yajl-ruby (~> 1.1.0)
        rack (1.5.2)
        rack-protection (1.5.0)
          rack
        rake (0.9.2.2)
        rb-fsevent (0.9.1)
        rdiscount (2.0.7.3)
        rubypants (0.2.0)
        sass (3.2.9)
        sass-globbing (1.0.0)
          sass (>= 3.1)
        sinatra (1.4.2)
          rack (~> 1.5, >= 1.5.2)
          rack-protection (~> 1.4)
          tilt (~> 1.3, >= 1.3.4)
        stringex (1.4.0)
        syntax (1.0.0)
        tilt (1.3.7)
        yajl-ruby (1.1.0)
        yajl-ruby (1.1.0-x86-mingw32)

    PLATFORMS
      ruby
      x64-mingw32
      x86-mingw32

    DEPENDENCIES
      RedCloth (~> 4.2.9)
      compass (~> 0.12.2)
      directory_watcher (= 1.4.1)
      haml (~> 3.1.7)
      jekyll (~> 0.12)
      liquid (~> 2.3.0)
      pygments.rb (~> 0.3.4)
      rake (~> 0.9)
      rb-fsevent (~> 0.9)
      rdiscount (~> 2.0.7)
      rubypants (~> 0.2.0)
      sass (~> 3.2)
      sass-globbing (~> 1.0.0)
      sinatra (~> 1.4.2)
      stringex (~> 1.4.0)

    BUNDLED WITH
       1.10.6
```

**Comment by ZachSaucier** [comment]
I get the same behavior on my desktop and laptop, running the same Windows 10 fast release version

**Comment by ZachSaucier** [comment]
I just looked more closely into the other issues and it seems that [#4613](https://github.com/bundler/bundler/issues/4613) is the same, though I don't know what system they're on

**Comment by mathiasslawik** [comment]
Hi. I'm having the exact same issue with Windows 10 fast release using the Linux subsystem for Windows.

As a workaround, I added the "sticky bit" to the Bundler tmp directory like this:

`chmod +t -R  ~/.bundle/cache`

Now it works. The reason for this is that on a Windows drive, directories always have mode 777 per default.

However, this issue is caused by the Ruby tmpdir.rb trying to make sense of a world-writable directory which is not sticky.

**Comment by mathiasslawik** [comment]
I've raised this issue with Ruby core. I don't know if this is the right place, but I think it should not check for the sticky bit under the Windows 10 Subsystem for Linux, as the permissions are handled by other OS parts:

https://bugs.ruby-lang.org/issues/12456

**Comment by colinrubbert** [comment]
I'd just like to confirm that the `chmod +t -R ~/.bundle/cache` worked for me on the Anniversary edition release for Windows 10, also worked on the insider preview release.

**Comment by thekayness** [comment]
I'm so glad I'm not the only one using the Ubuntu bash in Windows with this stuff!  Thanks for putting this out there, saved me a lot of trouble today.

**Comment by japborst** [comment]
@colinrubbert this returns some error for me. Any thoughts?

```
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/mime-types’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/shotgun’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info-special-characters’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info-special-characters/CFPropertyList-af6e634752764d9c328642293f28eaee’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info-special-characters/ParseTree-405fcd45b4c29adf532d2f46c40685b9’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info-special-characters/RubyInline-bb8de470fe25da785daa7103b796cbb0’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info-special-characters/SexpProcessor-279a3902a42d95552801b89581216e61’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info-special-characters/ZenTest-72d945c087709fb89086cd9a29466c4d’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info-special-characters/http_parser.rb-3d01dafd2e2dc7702495f6f06f360d49’: Operation not permitted
chmod: changing permissions of ‘/home/japborst/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info-special-characters/pygments.rb-42b367ab85b7ab16a84dd362096247e0’: Operation not permitted
```

**Comment by mattslay** [comment]
I just had the same issue...
  `chmod +t -R ~/.bundle/cache` worked fine for me.

**Comment by indirect** [comment]
This issue was fixed by https://github.com/bundler/bundler/pull/5043, and will be released soon in 1.13.3. Thanks for reporting it!

**Comment by suryapandian** [comment]
Same issue faced in Ubuntu changing the permission for ~/.bundle/cache doesnt seem to fix this issue here. Any help would be welcome.

**Comment by colby-swandale** [comment]
@suryapandian please open a new issue with the details of the problem you're having

**Comment by sunilpuranik** [comment]
Doing sudo chmod o-w tmp/ worked for me
