### ISSUE TITLE
bundle outdated (1.13.0) not listing all outdated gems

### ISSUE THREAD

**Issue by arturoherrero** [bundler/bundler#4979]
I've arrived in a new project and something weird was happening. I install Ruby (a little outdated, version 2.0.0) and I installed the latest version of Bundler (1.13.0), but the list of all outdated gems is really small compare with other college (he has installed Bundler 1.12.5).

Here is my output when I run bundle 1.13.0:

```
$ bundle -v
Bundler version 1.13.0

$ bundle outdated
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...............................................................................................

Outdated gems included in the bundle:
  * rspec-activemodel-mocks (newest 1.0.3, installed 1.0.1) in groups "test, development, ci"
  * hashery (newest 2.1.2, installed 2.1.1)
  * pdf-reader (newest 1.4.0, installed 1.3.3)
  * ttfunk (newest 1.2.2, installed 1.2.0)
```

And the output after I installed bundle 1.12.5:

```
$ bundle -v
Bundler version 1.12.5

$ bundle outdated
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...............................................................................................

Outdated gems included in the bundle:
  * actionpack-xml_parser (newest 2.0.0, installed 1.0.1) in group "default"
  * activerecord-session_store (newest 1.0.0, installed 0.1.0) in group "default"
  * aws-sdk (newest 2.5.11, installed 2.2.37, requested ~> 2.2) in group "default"
  * aws-sdk-v1 (newest 1.66.0, installed 1.64.0, requested < 2.0) in group "default"
  * bootstrap-sass (newest 3.3.7, installed 2.3.2.2, requested ~> 2.3.2) in group "default"
  * cancancan (newest 1.15.0, installed 1.8.4, requested ~> 1.8) in group "default"
  * capistrano (newest 3.6.1, installed 3.4.0, requested ~> 3.2) in group "development"
  ...
  ...
  ...
```

Any ideas? I expect to have the same behaviour between both versions.

**Comment by ansonhoyt** [comment]
I've been wondering why `bundle outdated` no longer matches what `bundle update` installs. I think this is the same problem.

```
$ bundler -v
Bundler version 1.13.1
$ rvm current
ruby-2.3.0@pbis
$ bundle outdated
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...

Outdated gems included in the bundle:
  * twitter-typeahead-rails (newest 0.11.1, installed 0.10.5, requested = 0.10.5) in group "default"
```

Based on this message, I would expect `bundle update` to install nothing here as the only outdated gem we see is locked to 0.10.5. However `bundle update` actually updated 42 gems:
```
Installing ffi 1.9.14 (was 1.9.10) with native extensions
Installing capistrano-harrow 0.5.3 (was 0.5.2)
Installing colorize 0.8.1 (was 0.7.7)
Installing daemons 1.2.4 (was 1.2.3)
...

I've been seeing this consistently across my projects since 1.13.0.

**Comment by chrismo** [comment]
can either of you share your `bundle env`?

**Comment by chrismo** [comment]
Appears to be introduced in [this commit](https://github.com/bundler/bundler/commit/cc3558650ed94c110ee1ab50ea75cd556dc188e9) ... restricting outdated output to matching platforms. 

Many of the specs in the index don't have a platform, so ... it ignores them:

![screen shot 2016-09-14 at 1 55 18 pm](https://cloud.githubusercontent.com/assets/8092/18525792/97eec2bc-7a83-11e6-81e1-4d49444c09a2.png)

But I dunno any about how those appear in the definition index and if something changed there out from underneath the code change in outdated, or if the change in outdated didn't take this sort of real world scenario into account.

I was curious about this bug, in case it was related to https://github.com/bundler/bundler/issues/4974 - but doesn't appear to be. (fwiw, I don't think I'll have bandwidth to look at this more, in light of other issues I've queued up for myself).

**Comment by chrismo** [comment]
It was easy to quickly check this against 1.12.5, so nothing was different then in terms of platform assignments to index results:

![screen shot 2016-09-14 at 2 14 24 pm](https://cloud.githubusercontent.com/assets/8092/18526323/bb9fd474-7a85-11e6-9a41-ff5220ce1ff9.png)

**Comment by segiddins** [comment]
@chrismo if that commit is the issue, the fix should be to use `#match_platform` which handles nil

**Comment by lucasmazza** [comment]
@segiddins @chrismo `spec. match_platform` seems to fix this issue on my environment - any suggestions on how to test this through the `outdated_spec.rb` specs so I can submit a complete PR for this?

**Comment by toshimaru** [comment]
Same here. Is anyone working to fx this issue?

**Comment by Aqualon** [comment]
Not sure if it's related, but I also see differences between `bundle outdated` with rubygems.org and our internal gem server:

```
Outdated gems included in the bundle:
  * capistrano (newest 3.2.1, installed 2.15.9) in group "deployment"
  * rubocop (newest 0.44.1, installed 0.42.0) in groups "development, development_sandbox"
  * parser (newest 2.3.1.4, installed 2.3.1.2)
  * terminal-table (newest 1.7.3, installed 1.7.2)
```

```
Outdated gems included in the bundle:
  * capistrano (newest 3.6.0, installed 2.15.9) in group "deployment"
  * rails (newest 5.0.0, installed 4.2.7.1, requested = 4.2.7.1) in group "default"
  * rubocop (newest 0.44.1, installed 0.42.0) in groups "development, development_sandbox"
  * sanitize (newest 4.0.1, installed 2.0.6, requested ~> 2.0.6) in group "default"
  * actionmailer (newest 5.0.0, installed 4.2.7.1)
  * actionpack (newest 5.0.0, installed 4.2.7.1)
  * actionview (newest 5.0.0, installed 4.2.7.1)
  * activejob (newest 5.0.0, installed 4.2.7.1)
  * activemodel (newest 5.0.0.1, installed 4.2.7.1)
  * activerecord (newest 5.0.0.1, installed 4.2.7.1)
  * activesupport (newest 5.0.0.1, installed 4.2.7.1)
  * arel (newest 7.1.1, installed 6.0.3)
  * bunny (newest 2.3.0, installed 0.7.10)
  * parser (newest 2.3.1.4, installed 2.3.1.2)
  * rack (newest 2.0.1, installed 1.6.4)
  * rails-dom-testing (newest 2.0.1, installed 1.0.7)
  * railties (newest 5.0.0, installed 4.2.7.1)
  * redis (newest 3.3.1, installed 3.1.0)
  * selenium-webdriver (newest 3.0.0, installed 2.53.4)
  * slop (newest 4.2.0, installed 3.6.0)
  * terminal-table (newest 1.7.3, installed 1.7.2)
```

The rubygems.org list is much shorter, even so it should show the same versions. And in case of `capistrano` it also shows only version 3.2.1 as newest, while newest version is 3.6.1 (https://rubygems.org/gems/capistrano).

With bundler 1.12.5 I get the correct list

```
Outdated gems included in the bundle:
  * byebug (newest 9.0.6, installed 9.0.5, requested ~> 9.0.5) in groups "development, test"
  * capistrano (newest 3.6.1, installed 2.15.9) in group "deployment"
  * parallel_tests (newest 2.10.0, installed 2.9.0) in groups "development, test"
  * rails (newest 5.0.0.1, installed 4.2.7.1, requested = 4.2.7.1) in group "default"
  * rails-i18n (newest 5.0.1, installed 4.0.9, requested ~> 4.0.9) in group "default"
  * rubocop (newest 0.44.1, installed 0.42.0) in groups "development, development_sandbox"
  * sanitize (newest 4.4.0, installed 2.0.6, requested ~> 2.0.6) in group "default"
  * actionmailer (newest 5.0.0.1, installed 4.2.7.1)
  * actionpack (newest 5.0.0.1, installed 4.2.7.1)
  * actionview (newest 5.0.0.1, installed 4.2.7.1)
  * activejob (newest 5.0.0.1, installed 4.2.7.1)
  * activemodel (newest 5.0.0.1, installed 4.2.7.1)
  * activerecord (newest 5.0.0.1, installed 4.2.7.1)
  * activesupport (newest 5.0.0.1, installed 4.2.7.1)
  * arel (newest 7.1.4, installed 6.0.3)
  * http-cookie (newest 1.0.3, installed 1.0.2)
  * json (newest 2.0.2, installed 1.8.3)
  * nokogiri (newest 1.6.8.1, installed 1.6.8)
  * parser (newest 2.3.1.4, installed 2.3.1.2)
  * rack (newest 2.0.1, installed 1.6.4)
  * rails-dom-testing (newest 2.0.1, installed 1.0.7)
  * railties (newest 5.0.0.1, installed 4.2.7.1)
  * redis (newest 3.3.1, installed 3.1.0)
  * rspec-core (newest 3.5.4, installed 3.5.3)
  * ruby_dep (newest 1.5.0, installed 1.4.0)
  * slop (newest 4.4.1, installed 3.6.0)
  * terminal-table (newest 1.7.3, installed 1.7.2)
```

**Comment by chrismo** [comment]
@toshimaru, I'm trying to wrap up some other issues first (and have somewhat limited time at the moment) -  @lucasmazza might be working a PR? I don't have a suggestion off-hand on how to test it ... been a while since I did my digging into it.

**Comment by arturoherrero** [comment]
This issue seems to be resolved in some release. It is not happening on Bundler 1.13.6.

**Comment by fschwahn** [comment]
That's not the case for me, with `1.13.6` this error if still happening.

**Comment by lucasmazza** [comment]
@arturoherrero @fschwahn I have the feeling that this was fixed on the server side of the API. I noticed that the `bundle outdated` output was changed after removing the cache from `~/.bundle/cache`, and now I can't replicate the issue anymore.

**Comment by ansonhoyt** [comment]
@lucasmazza what does clearing `~/.bundle/cache` do?

Like @fschwahn, this is still happening for me with `1.13.6`, where nothing appears in `outdated` but then `update` installs gems:

```
$ bundle -v
Bundler version 1.13.6
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ rvm current
ruby-2.3.1@pa-promise

$ bundle outdated
...
Bundle up to date!

$ bundle update
...
Installing autoprefixer-rails 6.5.3 (was 6.5.2)
```

Since `1.13.?`, I noticed `bundle outdated` output changes if I reset `Gemfile.lock` after `bundle update` and then re-try `bundle outdated`. Now `outdated` matches `update`:

```
$ bundle outdated
...
Outdated gems included in the bundle:
  * autoprefixer-rails (newest 6.5.3, installed 6.5.2)
```

Is this like the output change you're seeing after clearing `~/.bundle/cache`? I thought it was a little curious that behavior changed after a reset.

**Comment by Petercopter** [comment]
Clearing the cache did the trick for me on `1.13.6`.

**Comment by rmehner** [comment]
Output version `1.12.5`:

```
Outdated gems included in the bundle:
  * jsonapi-renderer (newest 0.1.1.beta3, installed 0.1.1.beta1)
  * libv8 (newest 5.3.332.38.1, installed 3.16.14.15)
  * slop (newest 4.4.1, installed 3.6.0)
```

Cleared `~/.bundle/cache`, installed `1.13.6`, output now:

```
Bundle up to date!
```

and not a single outdated gem. So this still persists for me. Anything I can do to add more info to this issue? :) Thank you for bug hunting!

**Comment by dmke** [comment]
Same here (1.12.6 vs. 1.13.6), even after clearing cache (`rm -rf ~/.bundle/cache). I guess #5176 will be available with 1.14?

**Comment by chrismo** [comment]
that's the current plan

**Comment by jaredbeck** [comment]
@chrismo I'd be happy to try to backport this to 1.13. This bug prevents people from seeing e.g. security patches, so I'd like to help get a fix released. I'm concerned that, with all the open issues, that 1.14 is still a long way off. If I can get you a backport PR, would you please review it? Thanks.

**Comment by jaredbeck** [comment]
This issue was closed by #5176, whose main commit is cc3558650, which is in tag `v1.13.7`. So, I expected this issue to be fixed in release `1.13.7`. However, `bundle outdated` still produces incorrect output, as reported in #5201.

I am still able to use, as a workaround, `bundle update && git checkout . && bundle outdated`.

Should we reopen this or #5201? Thanks.

**Comment by segiddins** [comment]
This will be included in 1.14

**Comment by jaredbeck** [comment]
> This will be included in 1.14

Thanks Samuel. Would you be interested in a backport? 

> This bug prevents people from seeing e.g. security patches, so I'd like to help get a fix released. I'm concerned that, with all the open issues, that 1.14 is still a long way off.

Please let me know if I can help.

**Comment by segiddins** [comment]
I'm working on releasing 1.14 this week, I'd rather not have to do three releases in a week

**Comment by jaredbeck** [comment]
Based on the changelog, I think this fix is present in `1.14.0.pre.2`.

```bash
gem install bundler -v '1.14.0.pre.2'
```

I'm trying it out, will report any issues. Thanks, Samuel.
