### ISSUE TITLE
Bundler doesn't take current ruby version into account

### ISSUE THREAD

**Issue by felix-last** [bundler/bundler#5425]
Using ruby 1.9.3, I updated a gem in my Gemfile and ran `bundle install`. The result was something like this: `Gem::InstallError: net-ssh requires Ruby version >= 2.0.`. I had to manually find the last version of net-ssh which supports ruby 1.9.3, add it to my Gemfile explicitly and rerun, just to find the next gem which does not support my ruby version.
Can't bundler automatically find versions of the gem that support my ruby version? This has previously been requested in #2965.

Please let me know if any other information is required.

`bundle env` output:
```
Bundler 1.7.6
Ruby 1.9.3 (2014-11-13 patchlevel 551) [x86_64-linux]
Rubygems 2.4.3
rvm 1.27.0 (latest)
GEM_HOME /home/x/.rvm/gems/ruby-1.9.3-p551@x
GEM_PATH /home/x/.rvm/gems/ruby-1.9.3-p551@x:/home/x/.rvm/gems/ruby-1.9.3-p551@global
rubygems-bundler (1.4.4)
```

**Comment by colby-swandale** [comment]
Can you not add `net-ssh` to your Gemfile with the version set to the last known version to work on 1.9.3?

**Comment by felix-last** [comment]
Yes, that's a workaround, but I have to do this for every gem separately. Most of those gems are dependencies of my dependencies, so when requiring a gem with many dependencies it can be many, many gems I have to find the last 1.9.3 supporting version of.
Shouldn't bundler free me of this hassle?

**Comment by segiddins** [comment]
It ought to if you update to 1.14.4

**Comment by jyanko** [comment]
Interesting. I came to file an issue about this, and someone has just recently done so!

I'm up against the same problem mentioned by this statement by @felix-last and I am using bundler version 1.14.3

> Most of those gems are dependencies of my dependencies...

I have recently been battling dependencies related to net-ssh as well in terms of getting capistrano installed into ruby 1.8.7 or 1.9.3 gemsets - which has had a fairly large impact on first time setup of deploy hosts recently.   

As reference, I'd previously opened an issue on the cap project here:
* https://github.com/capistrano/capistrano/issues/1844

After learning that bundler would allegedly be supporting a --conservative or --minimal-deps type functionality, I then started to tackle the problem by creating a custom Gemfile to setup deploy boxes.

* net-ssh versions >= 2.10 **REQUIRE** ruby >= 2.0
* setting the net-ssh version to < 2.10  in my Gemfile allowed me to get bundle install working  

Still, I have to manually identify gems and define them in my Gemfile that I feel like the dependency manager tool should be dealing with it for me.

As it stands, I'm going to have to deal with this across many many apps that are still supported in-house for these older ruby versions for now until they can be migrated to newer versions.  

## My environment
(I know, ruby 1.8.7, but similar issues with anything < ruby 2.0)

```
$ bundle env
Bundler   1.14.3
Rubygems  2.0.17
Ruby      1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
GEM_HOME  /usr/local/rvm/gems/ruby-1.8.7-p374@test_cap
GEM_PATH  /usr/local/rvm/gems/ruby-1.8.7-p374@test_cap:/usr/local/rvm/gems/ruby-1.8.7-p374@global
RVM       1.28.0 (manual)
Git       1.7.1
Platform  x86_64-linux
```

## Sample Gemsfiles and their bundle install results
Successful Gemfile:
```
$ cat Gemfile.deploy | egrep -v "^(source|$)"
group :deploy do
  gem "capistrano", "~> 2.15"
  gem "net-ssh", "< 2.10"
  gem "highline", "< 1.7"          # this line not needed for ruby >= 1.9.3
end
```
Gemfile resulting in: `highline-1.7.8 requires ruby version >= 1.9.3`
```
$ cat Gemfile.deploy | egrep -v "^(source|$)"
group :deploy do
  gem "capistrano", "~> 2.15"
end

$ cat Gemfile.deploy | egrep -v "^(source|$)"
group :deploy do
  gem "net-ssh", "< 4.0"
  gem "capistrano", "~> 2.15"
end
```

Gemfile resulting in: `net-ssh-3.2.0 requires ruby version >= 2.0`
```
$ cat Gemfile.deploy | egrep -v "^(source|$)"
group :deploy do
  gem "capistrano", "~> 2.15"
  gem "net-ssh", "< 4.0"
  gem "highline", "< 1.7"
end
```

**Comment by mattbrictson** [comment]
Using Bundler 1.14.4 and Ruby 1.9.3, I am still unable to get this to work:

```ruby
# Gemfile
source "https://rubygems.org"
gem "capistrano", "~> 2.15"
```

```
$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby (>= 2.0)

    ruby

Could not find gem 'ruby (>= 2.0)' in any of the sources
```

The work-around is to explicitly specify a version of `net-ssh` that is compatible with Ruby 1.9.3:

```ruby
# Gemfile
source "https://rubygems.org"
gem "capistrano", "~> 2.15"
gem "net-ssh", "< 4"
```

```
$ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using highline 1.7.8
Using net-ssh 2.9.4
Using bundler 1.14.4
Using net-scp 1.2.1
Using net-sftp 2.1.2
Using net-ssh-gateway 1.3.0
Using capistrano 2.15.9
Bundle complete! 2 Gemfile dependencies, 7 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

My environment:

```
Bundler   1.14.4
Rubygems  2.6.10
Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin15.6.0]
Git       2.11.1
Platform  x86_64-darwin-15
```

**Comment by jyanko** [comment]
With bundler 1.14.4 I see the same `Could not find gem 'ruby (>= 2.0)' in any of the sources` issue that @mattbrictson mentioned above with ruby 1.9.3 

Setting my Gemfile to define net-ssh as < 4.0 actually does work (note that for a ruby 1.8.7 target, I also have to specify the version of highline)...
```
group :deploy do
  gem "capistrano", "~> 2.15"
  gem "net-ssh", "< 4.0"
  gem "highline", "< 1.7"
end
```

Output from bundle install (when using rubygems.org as the source)
```
Resolving dependencies...
Rubygems 2.0.17 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Installing highline 1.6.21
Installing net-ssh 2.9.4
Using bundler 1.14.4
Installing net-scp 1.2.1
Installing net-sftp 2.1.2
Installing net-ssh-gateway 1.3.0
Installing capistrano 2.15.9
Bundle complete! 3 Gemfile dependencies, 7 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

However, if I point to a different local mirror as gem source, this same Gemfile fails various errors...

Here's a comparison of what I'm seeing with the different mirrors I have available locally


### SUCCESS: source=rubygems
```
$ gem list --source https://rubygems.org -ra 'net-ssh' | egrep '^net-ssh '
net-ssh (4.0.1, 4.0.0, 3.2.0, 3.1.1, 3.1.0, 3.0.2, 3.0.1, 2.9.4, 2.9.2...)

$ bundler install 
...
Resolving dependencies...
Rubygems 2.0.17 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Installing highline 1.6.21
Installing net-ssh 2.9.4
Using bundler 1.14.4
Installing net-scp 1.2.1
Installing net-sftp 2.1.2
Installing net-ssh-gateway 1.3.0
Installing capistrano 2.15.9
Bundle complete! 3 Gemfile dependencies, 7 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

### FAILURE: source=mirror_rf
```
$ gem list --source ${MIRROR_RF} -ra 'net-ssh' | egrep '^net-ssh '
net-ssh (4.0.1 ruby, 4.0.0 ruby, 3.2.0 ruby, 3.1.1 ruby, 3.1.0 ruby, 3.0.2 ruby, 3.0.1 ruby, 2.9.4 ruby, 2.9.2 ruby, 2.9.1 ruby...)

$ bundler install 
...
Resolving dependencies...
net-ssh-3.2.0 requires ruby version >= 2.0, which is incompatible with the current version, ruby 1.8.7p374
```

### FAILURE: source=mirror_at
```
$ gem list --source ${MIRROR_AT} -ra 'net-ssh' | egrep '^net-ssh '
net-ssh (4.0.1, 4.0.0, 3.2.0, 3.1.1, 3.1.0, 3.0.2, 3.0.1, 2.9.4, 2.9.2, 2.9.1...)

$ bundler install 
...
Could not find gem 'capistrano (~> 2.15)' in any of the gem sources listed in your Gemfile.

# odd, looks like several versions available to me...
$ gem list --source ${MIRROR_AT} -ra 'capistrano' | egrep '^capistrano '
capistrano (3.7.2, 3.7.1, 3.7.0, 3.6.1, 3.6.0, 3.5.0, 3.4.1, 3.4.0, 3.3.5, 3.3.4, 3.3.3, 3.2.1, 3.2.0, 3.1.0, 3.0.1, 3.0.0, 2.15.9, 2.15.8, 2.15.7, 2.15.6, 2.15.5, 2.15.4, 2.15.3, 2.15.2, 2.15.1, 2.15.0...)
```

### FAILURE: source=mirror_gh
```
$ gem list --source ${MIRROR_GH} -ra 'net-ssh' | egrep '^net-ssh '
net-ssh (4.0.1, 4.0.0, 3.2.0, 3.1.1, 3.1.0, 3.0.2, 3.0.1, 2.9.4, 2.9.2, 2.9.1...)

$ bundler install 
...
Could not find gem 'capistrano (~> 2.15)' in any of the gem sources listed in your Gemfile.
```

It's apparent I'll also need to be speaking with the maintainers of our internal mirrors related to this issue.

**Comment by segiddins** [comment]
Does your mirror serve the same compact index format as rubygems.org? Because that format is the only one that contains the relevant metadata for the resolver to respect ruby version requirements

**Comment by jyanko** [comment]
@segiddins - been speaking today with the maintainer of our internal mirror(s) and sounds like we don't support the dependency resolution API rubygems.org does ... so that's part of the problem I'm facing.  

Seems that anything I can pull from public rubygems.com works ok.   But non-public gems that require retrieval from our internal source(s) seem to create a problem when we have a Gemfile with mixed sources.

Even if I define rubygems.org as a source globally in the Gemfile...and then define the source on the same line for the internal gem ... it seems to break the install.

Internal maintainer is going to dig into the compact index issue to see if we can address that part or not internally.

Meanwhile, I'll see what I can do to find another workaround for getting internal gems to install and meet their dependencies.

**Comment by jyanko** [comment]
I was able to get a functioning Gemfile to get things installed from the multiple required gem sources.  

Gemfile that appears functional to install for ruby 1.8.7, 1.9.3, and 2.1.2
```
source "<public_gems_mirror>"
group :capistrano do
  gem "capistrano", "~> 2.15"
  gem "net-ssh", "<= 2.10.0"               # dependency for capistrano
  gem "highline", "< 1.7"                  # dependency for capistrano
end

group :internal do
  gem '<internal_gem>', '<version>' , :source => '<internal_gems_source_url>'
  gem "json", "~> 1.8"                      # dependency for <internal_gem>
end
```

Bundler Environment
```
Bundler   1.14.4
Rubygems  2.6.10
Ruby      1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
GEM_HOME  /usr/local/rvm/gems/ruby-1.8.7-p374@<gemset>
GEM_PATH  /usr/local/rvm/gems/ruby-1.8.7-p374@<gemset>:/usr/local/rvm/gems/ruby-1.8.7-p374@global
RVM       1.28.0 (manual)
Git       1.7.1
Platform  x86_64-linux
```
This allows me to at least get fresh hosts/gemsets tooled up to support deployments (whew).

Regardless of which gem source I'm pointing at, it seems that currently I *must* explicitly define the version restriction for both net-ssh and highline to support install to ruby 1.8.7 - for ruby 1.9.3 I may be able to exclude highline, but still need to have net-ssh defined.

As for the compact index format question...we'll be looking into that situation in-house since that appears to be an internal issue with our gem source mirror.

**Comment by segiddins** [comment]
Can confirm the issue reported in https://github.com/bundler/bundler/issues/5425#issuecomment-279577688

**Comment by segiddins** [comment]
https://github.com/CocoaPods/Molinillo/pull/60 should should fix this!

**Comment by segiddins** [comment]
This should be closed by https://github.com/bundler/bundler/pull/5495

**Comment by cben** [comment]
I can still reproduce on bundler 1.16.1, ruby 2.0 (I understand you might not care for EOL ruby 2.0, that's just the example I encountered, in case it's useful):

```
/tmp/t $ git clone https://github.com/abonas/kubeclient --branch v2.5.1
/tmp/t $ cd kubeclient/
/tmp/t/kubeclient ((v2.5.1)|✔) $ rbenv version
2.0.0-p648 (set by /tmp/t/.ruby-version)
/tmp/t/kubeclient ((v2.5.1)|✔) $ bundler -v
Bundler version 1.16.1
/tmp/t/kubeclient ((v2.5.1)|✔) $ bundle install
Fetching gem metadata from https://rubygems.org/................
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
RubyGems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to RubyGems 2.1.0 or higher to enable parallel gem installation.
Using rake 10.5.0
Fetching public_suffix 3.0.1
Installing public_suffix 3.0.1
Gem::InstallError: public_suffix requires Ruby version >= 2.1.
An error occurred while installing public_suffix (3.0.1), and Bundler cannot continue.
Make sure that `gem install public_suffix -v '3.0.1'` succeeds before bundling.

In Gemfile:
  kubeclient was resolved to 2.5.1, which depends on
    http was resolved to 0.9.8, which depends on
      addressable was resolved to 2.5.2, which depends on
        public_suffix

~/kubeclient ((v2.5.1)|…) $ ag public_suffix /home/bpaskinc/myenv/rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/addressable-2.5.2/
...
/home/bpaskinc/myenv/rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/addressable-2.5.2/tasks/gem.rake
23:    s.add_runtime_dependency 'public_suffix', '>= 2.0.2', '< 4.0'
```

https://rubygems.org/gems/public_suffix/versions/3.0.1 requires ruby >= 2.1.
https://rubygems.org/gems/public_suffix/versions/2.0.5 requires ruby >= 2.0.

## With public_suffix constrained
```
/tmp/t/kubeclient ((v2.5.1)|✔) $ echo 'gem "public_suffix", "~> 2.0"' >> Gemfile
/tmp/t/kubeclient ((v2.5.1)|✚1) $ cat Gemfile
source 'https://rubygems.org'

# Specify your gem's dependencies in kubeclient.gemspec
gemspec
gem "public_suffix", "~> 2.0"

/tmp/t/kubeclient ((v2.5.1)|✚1) $ bundle install
Fetching gem metadata from https://rubygems.org/................
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
RubyGems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to RubyGems 2.1.0 or higher to enable parallel gem installation.
Using rake 10.5.0
Using public_suffix 2.0.5
Using addressable 2.5.2
Using ast 2.3.0
Using parser 2.4.0.2
Fetching astrolabe 1.3.1
Installing astrolabe 1.3.1
Using bundler 1.16.1
Using safe_yaml 1.0.4
Using crack 0.4.3
Using unf_ext 0.0.7.4
Using unf 0.1.4
Using domain_name 0.5.20170404
Using hashdiff 0.3.7
Using http-cookie 1.0.3
Using http-form_data 1.0.3
Using http_parser.rb 0.6.0
Using http 0.9.8
Using recursive-open-struct 1.0.0
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using netrc 0.11.0
Using rest-client 2.0.2
Using kubeclient 2.5.1 from source at `.`
Using minitest 5.11.1
Using powerpack 0.1.1
Using rainbow 2.2.2
Using ruby-progressbar 1.9.0
Fetching rubocop 0.30.0
Installing rubocop 0.30.0
Using vcr 4.0.0
Fetching webmock 1.24.6
Installing webmock 1.24.6
Bundle complete! 8 Gemfile dependencies, 30 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
/tmp/t/kubeclient ((v2.5.1)|✚1) $ cat Gemfile.lock 
PATH
  remote: .
  specs:
    kubeclient (2.5.1)
      http (= 0.9.8)
      recursive-open-struct (= 1.0.0)
      rest-client

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    ast (2.3.0)
    astrolabe (1.3.1)
      parser (~> 2.2)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    hashdiff (0.3.7)
    http (0.9.8)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 1.0.1)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    http-form_data (1.0.3)
    http_parser.rb (0.6.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    minitest (5.11.1)
    netrc (0.11.0)
    parser (2.4.0.2)
      ast (~> 2.3)
    powerpack (0.1.1)
    public_suffix (2.0.5)
    rainbow (2.2.2)
      rake
    rake (10.5.0)
    recursive-open-struct (1.0.0)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rubocop (0.30.0)
      astrolabe (~> 1.3)
      parser (>= 2.2.0.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.4)
    ruby-progressbar (1.9.0)
    safe_yaml (1.0.4)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)
    vcr (4.0.0)
    webmock (1.24.6)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff

PLATFORMS
  ruby

DEPENDENCIES
  bundler (~> 1.6)
  kubeclient!
  minitest
  public_suffix (~> 2.0)
  rake (~> 10.0)
  rubocop (= 0.30.0)
  vcr
  webmock (~> 1.24.2)

BUNDLED WITH
   1.16.1
```

----

Note that only happens for development-mode `bundle install` inside kubeclient dir.
If I just make a Gemfile asking for kubeclient:
```
source 'https://rubygems.org'
gem 'kubeclient', '= 2.5.1'
```
I get successful install (following is for the `gem 'addressable'`):
```
/tmp/t $ bundle install
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
RubyGems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to RubyGems 2.1.0 or higher to enable parallel gem installation.
Using public_suffix 2.0.5
Using addressable 2.5.2
Using bundler 1.16.1
Using unf_ext 0.0.7.4
Using unf 0.1.4
Using domain_name 0.5.20170404
Using http-cookie 1.0.3
Using http-form_data 1.0.3
Using http_parser.rb 0.6.0
Using http 0.9.8
Using recursive-open-struct 1.0.0
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using netrc 0.11.0
Using rest-client 2.0.2
Using kubeclient 2.5.1
Bundle complete! 1 Gemfile dependency, 16 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
/tmp/t $ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    http (0.9.8)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 1.0.1)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    http-form_data (1.0.3)
    http_parser.rb (0.6.0)
    kubeclient (2.5.1)
      http (= 0.9.8)
      recursive-open-struct (= 1.0.0)
      rest-client
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    netrc (0.11.0)
    public_suffix (2.0.5)
    recursive-open-struct (1.0.0)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)

PLATFORMS
  ruby

DEPENDENCIES
  kubeclient (= 2.5.1)

BUNDLED WITH
   1.16.1
```

Similarly succeeds if I make Gemfile asking for the version of addressable in error message:
```
source 'https://rubygems.org'
gem 'addressable', '= 2.5.2'
```

**Comment by colby-swandale** [comment]
@cben please open a new issue
