### ISSUE TITLE
 bundle install

### ISSUE THREAD

**Issue by pengyuanhong** [bundler/bundler#5697]
bundle install
Error:
Downloading omniauth-google-oauth2-0.4.1 revealed dependencies not in the API or
the lockfile (omniauth-oauth2 (>= 1.3.1), jwt (~> 1.5.2)).
Either installing with `--full-index` or running `bundle update
omniauth-google-oauth2` should fix the problem.

bundle update  omniauth-google-oauth2
Error:
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
Please share the entire error report, thanks!

**Comment by pengyuanhong** [comment]
The problem has been solved. Switch the bundler version: 
gem install bundler --version '1.14.6' --no-ri --no-rdoc


Now comes a new problem:

bundle exec rake assets:precompile RAILS_ENV=production

Error:
Sass::SyntaxError: File to import not found or unreadable: ../../../node_modules/pikaday/scss/pikaday.
Load paths:
  /home/git/gitlab/app/assets/images
  /home/git/gitlab/app/assets/javascripts
  /home/git/gitlab/app/assets/stylesheets
  /home/git/gitlab/vendor/assets/fonts
  /home/git/gitlab/vendor/assets/javascripts
  /home/git/gitlab/vendor/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gettext_i18n_rails_js-1.2.0/lib/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gettext_i18n_rails_js-1.2.0/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/select2-rails-3.5.9.3/vendor/assets/images
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/select2-rails-3.5.9.3/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/select2-rails-3.5.9.3/vendor/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/jquery-rails-4.1.1/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/jquery-atwho-rails-1.3.2/lib/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/jquery-atwho-rails-1.3.2/lib/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/font-awesome-rails-4.7.0.1/app/assets/fonts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/font-awesome-rails-4.7.0.1/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/coffee-rails-4.1.1/lib/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mousetrap-rails-1.4.6/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mousetrap-rails-1.4.6/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/ace-rails-ap-4.1.2/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/underscore-rails-1.8.3/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/d3_rails-3.5.11/app/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/d3_rails-3.5.11/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/dropzonejs-rails-0.7.2/app/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/dropzonejs-rails-0.7.2/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/doorkeeper-4.2.0/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/doorkeeper-4.2.0/vendor/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gemojione-3.0.1/assets/png
  /home/git/gitlab/vendor/assets/fonts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/deckar01-task_list-1.0.6/app/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/deckar01-task_list-1.0.6/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/fonts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/images
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/stylesheets
/home/git/gitlab/app/assets/stylesheets/application.scss:21
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/import_node.rb:67:in `rescue in import'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/import_node.rb:45:in `import'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/import_node.rb:28:in `imported_file'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/import_node.rb:37:in `css_import?'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:313:in `visit_import'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:160:in `block in visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/stack.rb:79:in `block in with_base'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/stack.rb:115:in `with_frame'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/stack.rb:79:in `with_base'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:160:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `map'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:169:in `block in visit_children'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:181:in `with_environment'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:168:in `visit_children'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:188:in `visit_root'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:159:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:8:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/root_node.rb:36:in `css_tree'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/root_node.rb:20:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/engine.rb:281:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-rails-5.0.6/lib/sass/rails/template.rb:47:in `evaluate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/tilt-2.0.6/lib/tilt/template.rb:100:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Sass::SyntaxError: File to import not found or unreadable: ../../../node_modules/pikaday/scss/pikaday.
Load paths:
  /home/git/gitlab/app/assets/images
  /home/git/gitlab/app/assets/javascripts
  /home/git/gitlab/app/assets/stylesheets
  /home/git/gitlab/vendor/assets/fonts
  /home/git/gitlab/vendor/assets/javascripts
  /home/git/gitlab/vendor/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gettext_i18n_rails_js-1.2.0/lib/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gettext_i18n_rails_js-1.2.0/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/select2-rails-3.5.9.3/vendor/assets/images
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/select2-rails-3.5.9.3/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/select2-rails-3.5.9.3/vendor/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/jquery-rails-4.1.1/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/jquery-atwho-rails-1.3.2/lib/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/jquery-atwho-rails-1.3.2/lib/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/font-awesome-rails-4.7.0.1/app/assets/fonts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/font-awesome-rails-4.7.0.1/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/coffee-rails-4.1.1/lib/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mousetrap-rails-1.4.6/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mousetrap-rails-1.4.6/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/ace-rails-ap-4.1.2/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/underscore-rails-1.8.3/vendor/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/d3_rails-3.5.11/app/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/d3_rails-3.5.11/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/dropzonejs-rails-0.7.2/app/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/dropzonejs-rails-0.7.2/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/doorkeeper-4.2.0/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/doorkeeper-4.2.0/vendor/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gemojione-3.0.1/assets/png
  /home/git/gitlab/vendor/assets/fonts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/deckar01-task_list-1.0.6/app/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/deckar01-task_list-1.0.6/app/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/stylesheets
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/javascripts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/fonts
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/images
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/bootstrap-sass-3.3.6/assets/stylesheets
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/import_node.rb:65:in `import'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/import_node.rb:28:in `imported_file'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/import_node.rb:37:in `css_import?'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:313:in `visit_import'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:160:in `block in visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/stack.rb:79:in `block in with_base'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/stack.rb:115:in `with_frame'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/stack.rb:79:in `with_base'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:160:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `map'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:169:in `block in visit_children'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:181:in `with_environment'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:168:in `visit_children'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:188:in `visit_root'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:159:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/visitors/perform.rb:8:in `visit'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/root_node.rb:36:in `css_tree'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/tree/root_node.rb:20:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-3.4.22/lib/sass/engine.rb:281:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sass-rails-5.0.6/lib/sass/rails/template.rb:47:in `evaluate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/tilt-2.0.6/lib/tilt/template.rb:100:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

**Comment by colby-swandale** [comment]
This looks like a problem with Gitlab and not Bundler.

**Comment by duderamos** [comment]
Downgrading `bundler` from `1.15.1` to `1.14.6` worked for me.

**Comment by colby-swandale** [comment]
@duderamos we merged a change in master that should fix the problem in the original comment. If you can test bundler on the `master` branch it would be greatly appreciated. Thanks.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you have any more issues or questions feel free to open a new issue.

**Comment by BMorearty** [comment]
@colby-swandale I just encountered the original error too:

```
Downloading airbnb-currency-4.0.0 revealed dependencies not in the API or the lockfile (airbnb-alchemist-client (>= 0.0.0)).
Either installing with `--full-index` or running `bundle update airbnb-currency` should fix the problem.
```

So I tried your advice, testing bundler on the `master` branch, and it did not fix it. These are the steps I used:

1. `gem uninstall bundler` (remove all versions)
2. `git clone git@github.com:bundler/bundler.git` and `cd bundler`
3. `gem build bundler.gemspec` - this builds `bundler-1.15.1.gem` (presumably because you haven't yet bumped bundler's version for the next release)
4. `gem install bundler-1.15.1.gem`
5. Go to my project and `bundle`

RESULT: still same error.

Please let me know if I did the steps wrong.

**Comment by colby-swandale** [comment]
@BMorearty can you please open a new issue with this information and include the output of `bundle env`. Thanks!

**Comment by BMorearty** [comment]
@colby-swandale I'm not comfortable posting that much closed-source code. Maybe I can try to create a small repro case.

**Comment by BMorearty** [comment]
I'm not having luck with this. 😢

**Comment by chrismo** [comment]
Can you double-check that 'airbnb-alchemist-client' is published to your gem server?

**Comment by BMorearty** [comment]
I've double-checked. 'airbnb-alchemist-client' is published to our gem server. Also, downgrading to Bundler 1.14.6 eliminates the error and bundles correctly. But I can't bundle with 1.15.1 or with master.

**Comment by chrismo** [comment]
#5846 also appears to be a similar bug report ... ?

**Comment by dcorking** [comment]
@BMorearty @pengyuanhong Did you fix (or work around) your issues? If so, what was the fix? 

(I ask because I also have a lockfile, that I can't post, that does not `install` with 1.15.4 or 1.16.0.pre.2, that may have been corrupted by Bundler 1.14.6)

**Comment by BMorearty** [comment]
@dcorking Our workaround at Airbnb was not to upgrade bundler beyond 1.14.6. 😢

**Comment by indirect** [comment]
@dcorking @BMorearty have you tried installing with `bundle install --full-index`? If that doesn't work, can you help us figure out what's going on? I can swing by the Airbnb office if the repro case needs to stay private.

**Comment by BMorearty** [comment]
@indirect Yes, I did try `bundle install --full-index` when I first encountered this error. I noticed that suggestion in the error message. But it did not help.

I'd be happy to have you swing by the Airbnb office to look at a repro case. The last time I encountered the error was today, on another engineer's machine. After I asked him to downgrade to 1.14.6 the error went away.

Let's do this: I will install 1.15.4 and let you know when I next encounter the error. It will likely not be this week since I'm not coding a lot this week. Is this thread a good way to reach you?

**Comment by indirect** [comment]
@BMorearty sounds good. drop me an email at andre@arko.net when you're ready, and we can set something up.
